# Generated by Django 3.2.8 on 2021-11-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_rename_added_date_order_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='pos_app.Category'),
        ),
    ]
